let places:string[]=["Japan","China","france","America","New Zealand"];
console.log("Original order:",places);
console.log("Alphabetical order:",[...places].sort());
console.log("Original order:",places);
console.log("Reverse alphabetical order:",[...places].sort().reverse());
console.log("Orignal order:",places);
places.reverse();
console.log("Reversed order:",places);
places.reverse();
console.log("Orignal order:",places);
places.sort();
console.log("Alphabetical order:",places);
places.reverse();
console.log("Reverse alphabetical order:",places);